[package]
name = "cross-compile"
version = "0.1.0"
edition = "2021"

[dependencies]
dagger-sdk = "0.9.8"
eyre = "0.6.12"
tokio = { version = "1.37.0", features = ["full"] }
tracing-subscriber = "0.3.18"
